#eureka service center address list , split
#get service registry list from service center
#auto update registry list time

eureka:
  instance:
  ip-address: 39.108.65.230
  prefer-ip-address: true
  client:
    fetchRegistry: true
    registryFetchIntervalSeconds: 10
    serviceUrl: 
      defaultZone: http://39.108.65.230:8100/eureka/,http://39.108.164.199:8100/eureka/